export ETHEREUM_JSONRPC_VARIANT=mamba
export ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8546
export DATABASE_URL=postgresql://blockscout:blockscout@localhost:5432/blockscout
export INDEXER_DISABLE_ADDRESS_COIN_BALANCE_FETCHER=false
